name: Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Pega uma máquina virtual ubuntu para executar a automatização dentro dela

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Set up JDK 11 # Configurar o java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build com Maven # Instala as dependencias do projeto
        run: mvn clean install